name: auto_image_sequencer
description: "Animate a sequence of images"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0-9.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
